### ISSUE TITLE
Needs backup and restore process

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/adopt-a-drain#27]
As the App Maintainer I need a process for backing up and restoring data.

**Comment by ryayak1460** [comment]
@BretFisher This seems more Postgres and Docker related.  Any tips?

**Comment by BretFisher** [comment]
Since we're using Heroku's data services, restore and rollback are all [documented on their site](https://devcenter.heroku.com/articles/heroku-postgres-backups) and mostly a few clicks away. We use a free tier so we don't get much for that. At some point, we need a convo around the frequency of backups, how long we keep them, etc. A higher end plan gets us more backup storage and continual backups/failover if we need it.

Until now backups only happen when we click the backup button here: http://d.pr/i/oIJG7V/3kUnKj8n

The link at top shows an example of setting an auto backup daily. Our free plan supports 2 backup copies. *I've enabled daily for both `master` and `develop` norfolkdrains apps.

Other than planning for "our app gets deleted on heroku" that's it really. Before big prod launch we could go through an exercise of starting from scratch on a new heroku app and restoring db's, but not sure that's needed for these smaller launches given heroku's track record for keeping things working.
